export const ON_APPLICATION_START = "ON_APPLICATION_START";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const ON_LOGIN_START = "ON_LOGIN_START";
export const ON_LOGIN_SUCCESS = "ON_LOGIN_SUCCESS";
export const ON_LOGIN_FAIL = "ON_LOGIN_FAIL";

export const DOCS_FETCH_START = "DOCS_FETCH_START";
export const DOCS_FETCH_SUCCESS = "DOCS_FETCH_SUCCESS";
export const DOCS_FETCH_FAIL= "DOCS_FETCH_FAIL";

export const DOCS_UPLOAD_START = "DOCS_UPLOAD_START";
export const DOCS_UPLOAD_SUCCESS = "DOCS_UPLOAD_SUCCESS";
export const DOCS_UPLOAD_FAIL= "DOCS_UPLOAD_FAIL";

export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const DOCS_DOWNLOAD_START = "DOCS_DOWNLOAD_START";
export const DOC_UPLOAD_PROGRESS = "DOC_UPLOAD_PROGRESS";
